/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as ProductsSolsuiteRouteImport } from './routes/products/solsuite'
import { Route as ProductsSolstatusRouteImport } from './routes/products/solstatus'
import { Route as EnServicesRouteImport } from './routes/en/services'
import { Route as EnContactRouteImport } from './routes/en/contact'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as EnProductsIndexRouteImport } from './routes/en/products/index'
import { Route as EnProductsSolsuiteRouteImport } from './routes/en/products/solsuite'
import { Route as EnProductsSolstatusRouteImport } from './routes/en/products/solstatus'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSolsuiteRoute = ProductsSolsuiteRouteImport.update({
  id: '/products/solsuite',
  path: '/products/solsuite',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSolstatusRoute = ProductsSolstatusRouteImport.update({
  id: '/products/solstatus',
  path: '/products/solstatus',
  getParentRoute: () => rootRouteImport,
} as any)
const EnServicesRoute = EnServicesRouteImport.update({
  id: '/en/services',
  path: '/en/services',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProductsIndexRoute = EnProductsIndexRouteImport.update({
  id: '/en/products/',
  path: '/en/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProductsSolsuiteRoute = EnProductsSolsuiteRouteImport.update({
  id: '/en/products/solsuite',
  path: '/en/products/solsuite',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProductsSolstatusRoute = EnProductsSolstatusRouteImport.update({
  id: '/en/products/solstatus',
  path: '/en/products/solstatus',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/services': typeof EnServicesRoute
  '/products/solstatus': typeof ProductsSolstatusRoute
  '/products/solsuite': typeof ProductsSolsuiteRoute
  '/en/': typeof EnIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/en/products/solstatus': typeof EnProductsSolstatusRoute
  '/en/products/solsuite': typeof EnProductsSolsuiteRoute
  '/en/products/': typeof EnProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/services': typeof EnServicesRoute
  '/products/solstatus': typeof ProductsSolstatusRoute
  '/products/solsuite': typeof ProductsSolsuiteRoute
  '/en': typeof EnIndexRoute
  '/products': typeof ProductsIndexRoute
  '/en/products/solstatus': typeof EnProductsSolstatusRoute
  '/en/products/solsuite': typeof EnProductsSolsuiteRoute
  '/en/products': typeof EnProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/services': typeof EnServicesRoute
  '/products/solstatus': typeof ProductsSolstatusRoute
  '/products/solsuite': typeof ProductsSolsuiteRoute
  '/en/': typeof EnIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/en/products/solstatus': typeof EnProductsSolstatusRoute
  '/en/products/solsuite': typeof EnProductsSolsuiteRoute
  '/en/products/': typeof EnProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/en/about'
    | '/en/contact'
    | '/en/services'
    | '/products/solstatus'
    | '/products/solsuite'
    | '/en/'
    | '/products/'
    | '/en/products/solstatus'
    | '/en/products/solsuite'
    | '/en/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/en/about'
    | '/en/contact'
    | '/en/services'
    | '/products/solstatus'
    | '/products/solsuite'
    | '/en'
    | '/products'
    | '/en/products/solstatus'
    | '/en/products/solsuite'
    | '/en/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/en/about'
    | '/en/contact'
    | '/en/services'
    | '/products/solstatus'
    | '/products/solsuite'
    | '/en/'
    | '/products/'
    | '/en/products/solstatus'
    | '/en/products/solsuite'
    | '/en/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EnAboutRoute: typeof EnAboutRoute
  EnContactRoute: typeof EnContactRoute
  EnServicesRoute: typeof EnServicesRoute
  ProductsSolstatusRoute: typeof ProductsSolstatusRoute
  ProductsSolsuiteRoute: typeof ProductsSolsuiteRoute
  EnIndexRoute: typeof EnIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  EnProductsSolstatusRoute: typeof EnProductsSolstatusRoute
  EnProductsSolsuiteRoute: typeof EnProductsSolsuiteRoute
  EnProductsIndexRoute: typeof EnProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/solsuite': {
      id: '/products/solsuite'
      path: '/products/solsuite'
      fullPath: '/products/solsuite'
      preLoaderRoute: typeof ProductsSolsuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/solstatus': {
      id: '/products/solstatus'
      path: '/products/solstatus'
      fullPath: '/products/solstatus'
      preLoaderRoute: typeof ProductsSolstatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/services': {
      id: '/en/services'
      path: '/en/services'
      fullPath: '/en/services'
      preLoaderRoute: typeof EnServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/products/': {
      id: '/en/products/'
      path: '/en/products'
      fullPath: '/en/products/'
      preLoaderRoute: typeof EnProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/products/solsuite': {
      id: '/en/products/solsuite'
      path: '/en/products/solsuite'
      fullPath: '/en/products/solsuite'
      preLoaderRoute: typeof EnProductsSolsuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/products/solstatus': {
      id: '/en/products/solstatus'
      path: '/en/products/solstatus'
      fullPath: '/en/products/solstatus'
      preLoaderRoute: typeof EnProductsSolstatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EnAboutRoute: EnAboutRoute,
  EnContactRoute: EnContactRoute,
  EnServicesRoute: EnServicesRoute,
  ProductsSolstatusRoute: ProductsSolstatusRoute,
  ProductsSolsuiteRoute: ProductsSolsuiteRoute,
  EnIndexRoute: EnIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  EnProductsSolstatusRoute: EnProductsSolstatusRoute,
  EnProductsSolsuiteRoute: EnProductsSolsuiteRoute,
  EnProductsIndexRoute: EnProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
